### ISSUE TITLE
Parentheses in matrices aren't displayed correctly

### ISSUE THREAD

**Issue by xlf1024** [runarberg/ascii2mathml#16]
`{:(A),(B);(C),(D);:}`
renders to
``` xml
<math display="block">
  <mfenced open="" close="">
    <mtable>
      <mtr>
        <mtd><mi>A</mi></mtd>
      </mtr>
      <mtr>
        <mtd><mi>B</mi><mi>)</mi><mo>;</mo><mfenced open="(" close=""><mi>C</mi></mfenced></mtd>
      </mtr>
      <mtr>
        <mtd><mi>D</mi><mi>)</mi></mtd>
      </mtr>
    </mtable>
  </mfenced>
</math>
```
instead of the expected
``` xml
<math display="block">
  <mfenced open="" close="">
    <mtable>
      <mtr>
        <mtd><mfenced open="(" close=")"><mi>A</mi></mfenced></mtd>
        <mtd><mfenced open="(" close=")"><mi>B</mi></mfenced></mtd>
      </mtr>
      <mtr>
        <mtd><mfenced open="(" close=")"><mi>C</mi></mfenced></mtd>
        <mtd><mfenced open="(" close=")"><mi>D</mi></mfenced></mtd>
      </mtr>
    </mtable>
  </mfenced>
</math>
```
which can be approximated by adding an escaped whitespace before the first comma: `{:(A)\ ,(B);(C),(D);:}`
(this workaround adds an extra invisible `<mrow>` with an whitespace `<mo>` in it)

**Comment by xlf1024** [comment]
ASCII-Art-Approximation:
```
  A
B);(C
  D)
```
instead of
```
(A) (B)
(C) (D)
```

**Comment by runarberg** [comment]
This is an annoying bug indeed. It seems as if the two matrix syntaxes are clashing with each other. In my opinion the comma, semicolon syntax should take precedence.

If I find time I might try to fix that (@xlf1024 if you want to have a go at it your self, you are welcome to). In the mean time you can use the nested parentheses syntax:

```
{:[(A), (B)], [(C), (D)]:}
```

**Comment by xlf1024** [comment]
I guess after having survived my exams, I'll learn how git and babel and the other tools you use actually work and try my best. But don't expect high-quality code, I consider myself still a beginner.

(I'm using this in combination with markdown-it for my lecture notes btw.)

Actually, I fear, that the only "solution" for this will be adding an option to choose between the two syntaxes, as otherwise there would be some ambiguous cases. The only other solution would be looking for the existence of  semicolons and then dynamically disabling the nested parentheses syntax, but I fear that this will be quite unreliable, especially with nested matrices, which occur quite often in what I write, as I use non-fenced matrices for layout quite often.
And, by the way, I prefer the semicolon syntax, too, as it is (at least seems) less complicated when nesting matrices.

**Comment by xlf1024** [comment]
On the other hand, the nested parentheses syntax is apparently the one supported by asciimath.org and MathJax, so removing it would increase the incompatibilities. (So far there's only stuff that only works here but nothing that only works in MathJax).

**Comment by runarberg** [comment]
@xlf1024 I was indeed still a beginner when I wrote this library, and I still consider myself a noob when it comes to compilers.

I don’t think we a configuration to select one of the syntaxes. Markdown is an example of a language that is seemingly full of ambiguities but still they are able to write down a [complete standard](http://commonmark.org/) that resolves all of them. I think the second options is preferred.

I think the bug is simply a bug in scanning the delimiters. If this is a semicolon (or newline) separated matrix, we need to not scan for closing parenthesis for closing the row.

There are few inconsistencies between this and asciimath (see #10 for example). I try to keep them at minimum. Although sometimes I’m not too happy with the syntax choose of asciimath (`^^` for logical conjunction ‘∧’, instead of `<mover>`) and in the case of `bb` instead of `bf` as boldface I decided to intentionally brake compatibility 😄. But overall I still would like to support most things asciimath supports.
